/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRfqParsingRouteImport } from './routes/_app.rfq-parsing'
import { Route as AppRfqInboxRouteImport } from './routes/_app.rfq-inbox'
import { Route as AppRevisionsRouteImport } from './routes/_app.revisions'
import { Route as AppReviewRouteImport } from './routes/_app.review'
import { Route as AppQuotesRouteImport } from './routes/_app.quotes'
import { Route as AppProcurementRouteImport } from './routes/_app.procurement'
import { Route as AppPoHandoffRouteImport } from './routes/_app.po-handoff'
import { Route as AppParallelEvaluationRouteImport } from './routes/_app.parallel-evaluation'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppMastersRouteImport } from './routes/_app.masters'
import { Route as AppDrawingsRouteImport } from './routes/_app.drawings'
import { Route as AppCostingRouteImport } from './routes/_app.costing'
import { Route as AppBomRouteImport } from './routes/_app.bom'
import { Route as AppAuditLogsRouteImport } from './routes/_app.audit-logs'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRfqParsingRoute = AppRfqParsingRouteImport.update({
  id: '/rfq-parsing',
  path: '/rfq-parsing',
  getParentRoute: () => AppRoute,
} as any)
const AppRfqInboxRoute = AppRfqInboxRouteImport.update({
  id: '/rfq-inbox',
  path: '/rfq-inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppRevisionsRoute = AppRevisionsRouteImport.update({
  id: '/revisions',
  path: '/revisions',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotesRoute = AppQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AppRoute,
} as any)
const AppProcurementRoute = AppProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => AppRoute,
} as any)
const AppPoHandoffRoute = AppPoHandoffRouteImport.update({
  id: '/po-handoff',
  path: '/po-handoff',
  getParentRoute: () => AppRoute,
} as any)
const AppParallelEvaluationRoute = AppParallelEvaluationRouteImport.update({
  id: '/parallel-evaluation',
  path: '/parallel-evaluation',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMastersRoute = AppMastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => AppRoute,
} as any)
const AppDrawingsRoute = AppDrawingsRouteImport.update({
  id: '/drawings',
  path: '/drawings',
  getParentRoute: () => AppRoute,
} as any)
const AppCostingRoute = AppCostingRouteImport.update({
  id: '/costing',
  path: '/costing',
  getParentRoute: () => AppRoute,
} as any)
const AppBomRoute = AppBomRouteImport.update({
  id: '/bom',
  path: '/bom',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogsRoute = AppAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/bom': typeof AppBomRoute
  '/costing': typeof AppCostingRoute
  '/drawings': typeof AppDrawingsRoute
  '/masters': typeof AppMastersRoute
  '/notifications': typeof AppNotificationsRoute
  '/parallel-evaluation': typeof AppParallelEvaluationRoute
  '/po-handoff': typeof AppPoHandoffRoute
  '/procurement': typeof AppProcurementRoute
  '/quotes': typeof AppQuotesRoute
  '/review': typeof AppReviewRoute
  '/revisions': typeof AppRevisionsRoute
  '/rfq-inbox': typeof AppRfqInboxRoute
  '/rfq-parsing': typeof AppRfqParsingRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesByTo {
  '/audit-logs': typeof AppAuditLogsRoute
  '/bom': typeof AppBomRoute
  '/costing': typeof AppCostingRoute
  '/drawings': typeof AppDrawingsRoute
  '/masters': typeof AppMastersRoute
  '/notifications': typeof AppNotificationsRoute
  '/parallel-evaluation': typeof AppParallelEvaluationRoute
  '/po-handoff': typeof AppPoHandoffRoute
  '/procurement': typeof AppProcurementRoute
  '/quotes': typeof AppQuotesRoute
  '/review': typeof AppReviewRoute
  '/revisions': typeof AppRevisionsRoute
  '/rfq-inbox': typeof AppRfqInboxRoute
  '/rfq-parsing': typeof AppRfqParsingRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/audit-logs': typeof AppAuditLogsRoute
  '/_app/bom': typeof AppBomRoute
  '/_app/costing': typeof AppCostingRoute
  '/_app/drawings': typeof AppDrawingsRoute
  '/_app/masters': typeof AppMastersRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/parallel-evaluation': typeof AppParallelEvaluationRoute
  '/_app/po-handoff': typeof AppPoHandoffRoute
  '/_app/procurement': typeof AppProcurementRoute
  '/_app/quotes': typeof AppQuotesRoute
  '/_app/review': typeof AppReviewRoute
  '/_app/revisions': typeof AppRevisionsRoute
  '/_app/rfq-inbox': typeof AppRfqInboxRoute
  '/_app/rfq-parsing': typeof AppRfqParsingRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-logs'
    | '/bom'
    | '/costing'
    | '/drawings'
    | '/masters'
    | '/notifications'
    | '/parallel-evaluation'
    | '/po-handoff'
    | '/procurement'
    | '/quotes'
    | '/review'
    | '/revisions'
    | '/rfq-inbox'
    | '/rfq-parsing'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/audit-logs'
    | '/bom'
    | '/costing'
    | '/drawings'
    | '/masters'
    | '/notifications'
    | '/parallel-evaluation'
    | '/po-handoff'
    | '/procurement'
    | '/quotes'
    | '/review'
    | '/revisions'
    | '/rfq-inbox'
    | '/rfq-parsing'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/audit-logs'
    | '/_app/bom'
    | '/_app/costing'
    | '/_app/drawings'
    | '/_app/masters'
    | '/_app/notifications'
    | '/_app/parallel-evaluation'
    | '/_app/po-handoff'
    | '/_app/procurement'
    | '/_app/quotes'
    | '/_app/review'
    | '/_app/revisions'
    | '/_app/rfq-inbox'
    | '/_app/rfq-parsing'
    | '/_app/settings'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rfq-parsing': {
      id: '/_app/rfq-parsing'
      path: '/rfq-parsing'
      fullPath: '/rfq-parsing'
      preLoaderRoute: typeof AppRfqParsingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rfq-inbox': {
      id: '/_app/rfq-inbox'
      path: '/rfq-inbox'
      fullPath: '/rfq-inbox'
      preLoaderRoute: typeof AppRfqInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/revisions': {
      id: '/_app/revisions'
      path: '/revisions'
      fullPath: '/revisions'
      preLoaderRoute: typeof AppRevisionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review': {
      id: '/_app/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotes': {
      id: '/_app/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof AppQuotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/procurement': {
      id: '/_app/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof AppProcurementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/po-handoff': {
      id: '/_app/po-handoff'
      path: '/po-handoff'
      fullPath: '/po-handoff'
      preLoaderRoute: typeof AppPoHandoffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parallel-evaluation': {
      id: '/_app/parallel-evaluation'
      path: '/parallel-evaluation'
      fullPath: '/parallel-evaluation'
      preLoaderRoute: typeof AppParallelEvaluationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/masters': {
      id: '/_app/masters'
      path: '/masters'
      fullPath: '/masters'
      preLoaderRoute: typeof AppMastersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/drawings': {
      id: '/_app/drawings'
      path: '/drawings'
      fullPath: '/drawings'
      preLoaderRoute: typeof AppDrawingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/costing': {
      id: '/_app/costing'
      path: '/costing'
      fullPath: '/costing'
      preLoaderRoute: typeof AppCostingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bom': {
      id: '/_app/bom'
      path: '/bom'
      fullPath: '/bom'
      preLoaderRoute: typeof AppBomRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-logs': {
      id: '/_app/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AppAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAuditLogsRoute: typeof AppAuditLogsRoute
  AppBomRoute: typeof AppBomRoute
  AppCostingRoute: typeof AppCostingRoute
  AppDrawingsRoute: typeof AppDrawingsRoute
  AppMastersRoute: typeof AppMastersRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppParallelEvaluationRoute: typeof AppParallelEvaluationRoute
  AppPoHandoffRoute: typeof AppPoHandoffRoute
  AppProcurementRoute: typeof AppProcurementRoute
  AppQuotesRoute: typeof AppQuotesRoute
  AppReviewRoute: typeof AppReviewRoute
  AppRevisionsRoute: typeof AppRevisionsRoute
  AppRfqInboxRoute: typeof AppRfqInboxRoute
  AppRfqParsingRoute: typeof AppRfqParsingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditLogsRoute: AppAuditLogsRoute,
  AppBomRoute: AppBomRoute,
  AppCostingRoute: AppCostingRoute,
  AppDrawingsRoute: AppDrawingsRoute,
  AppMastersRoute: AppMastersRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppParallelEvaluationRoute: AppParallelEvaluationRoute,
  AppPoHandoffRoute: AppPoHandoffRoute,
  AppProcurementRoute: AppProcurementRoute,
  AppQuotesRoute: AppQuotesRoute,
  AppReviewRoute: AppReviewRoute,
  AppRevisionsRoute: AppRevisionsRoute,
  AppRfqInboxRoute: AppRfqInboxRoute,
  AppRfqParsingRoute: AppRfqParsingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
